# Generated by Django 3.0.4 on 2020-04-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='bug_name', max_length=100)),
                ('location', models.CharField(default='bug_location', max_length=100)),
                ('rarity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_caught', models.BooleanField(default=False)),
                ('January', models.BooleanField(default=False)),
                ('February', models.BooleanField(default=False)),
                ('March', models.BooleanField(default=False)),
                ('April', models.BooleanField(default=False)),
                ('May', models.BooleanField(default=False)),
                ('June', models.BooleanField(default=False)),
                ('July', models.BooleanField(default=False)),
                ('August', models.BooleanField(default=False)),
                ('September', models.BooleanField(default=False)),
                ('October', models.BooleanField(default=False)),
                ('November', models.BooleanField(default=False)),
                ('December', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_time_2', models.TimeField(blank=True, null=True)),
                ('end_time_2', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='fish_name', max_length=100)),
                ('location', models.CharField(default='fish_location', max_length=100)),
                ('rarity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('shadow_size', models.IntegerField(default=0)),
                ('is_caught', models.BooleanField(default=False)),
                ('January', models.BooleanField(default=False)),
                ('February', models.BooleanField(default=False)),
                ('March', models.BooleanField(default=False)),
                ('April', models.BooleanField(default=False)),
                ('May', models.BooleanField(default=False)),
                ('June', models.BooleanField(default=False)),
                ('July', models.BooleanField(default=False)),
                ('August', models.BooleanField(default=False)),
                ('September', models.BooleanField(default=False)),
                ('October', models.BooleanField(default=False)),
                ('November', models.BooleanField(default=False)),
                ('December', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_time_2', models.TimeField(blank=True, null=True)),
                ('end_time_2', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
