# Generated by Django 3.0.4 on 2020-04-26 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0003_auto_20200426_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(default='00000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('bugs', models.CharField(default='00000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('paintings', models.CharField(default='00000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
